version: "2"
services:
   mongo:
     image: tutum/mongodb
     ports:
       - "27017"
     command: mongod --smallfiles --rest --logpath=/dev/null
   web:
     build: .
     links:
       - mongo
     command: node server.js
     ports:
       - "3007:3006"
     environment:
       - DbUrl=mongodb://mongo/facts
